server:
  port: 8085

spring:
  application:
    name: pdd-lottery-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:pdd_flash_sale}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:pdd}
    password: ${RABBITMQ_PASSWORD:pdd123456}
    publisher-confirm-type: correlated
    publisher-returns: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

pdd:
  worker-id: 5
  lottery:
    draw-cron: ${LOTTERY_DRAW_CRON:0 45 20 18 6 ?}
  jwt:
    secret: ${JWT_SECRET:pdd-flash-sale-platform-secret-key-must-be-32-bytes}
